services:
  postgres:
    image: postgres:18beta1
    container_name: postgres18-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring-network

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest-api
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring-network

  springboot-app:
    build: .
    container_name: meangsreang-app
    restart: always
    ports:
      - "${APP_PORT}:9091"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BAKONG_MERCHANT_ID: ${BAKONG_ACCOUNT_ID}
      BAKONG_MERCHANT_NAME: ${BAKONG_MERCHANT_NAME}
      BAKONG_MERCHANT_CITY: ${BAKONG_MERCHANT_CITY}
      BAKONG_API_URL: ${BAKONG_API_URL}
      BAKONG_TOKEN: ${BAKONG_TOKEN}
    networks:
      - spring-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  spring-network:
    driver: bridge